### ISSUE TITLE
Android DI 프레임 워크 선정

### ISSUE THREAD

**Issue by zionzizon** [Vallista/StartIsHalf#3]
[Realm Android Weekly #196 해석](https://realm.io/kr/news/android-weekly-kr-196/) 에 따르면 Roboguice, Dagger1, Dagger2 들 에 대한 벤치마크 자료들을 제공한다. 즉 이 3가지가 제일 화두 인걸로 예측 가능하다. 1년 이 안된 dicussion 된 자료는 없는 듯하다. [DI 벤치마크 자료](http://blog.nimbledroid.com/2016/03/07/performance-of-dependency-injection-libraries.html) 에 따르면 roboguise 는 무겁고 dagger2 가 dagger1 보다는 나으니 dagger2 를 추천한다고 쓰여져 있다.

**Comment by ZiZoNZZMAN** [comment]
dagger2 와 같이 쓰이는 butterknife DI 프레임 워크가 있는데 RxBinding 와 어느정도 치환될만한 녀석이다. View 할당 및 이벤트 설정에 쓰일 듯 하다.

**Comment by ZiZoNZZMAN** [comment]
dagger2 + butterknife 로 결정.

**Comment by ZiZoNZZMAN** [comment]
DataBinding 이라는 DI가 있다. 기능은  butterknife 비슷함. 선별해야할 가치가 맀는듯

**Comment by ZiZoNZZMAN** [comment]
[dataBinding 에 대한 critic한 의견](https://medium.com/@Miqubel/4-reasons-im-not-using-android-data-binding-e62127c2650c#.54y60oesd) 을 보면 코드가 xml 안에 들어가는게 영 맘에 안드나보다. 하지만 원래 layout에 강결합 상태로 붙어 있어 무조건 이 글의 뜻에 따를순 없다.

**Comment by zionzizon** [comment]
하지만 아무래도 레이아웃 정보에 로직이 들어간다는건 끔찍한 것 같다. butterknife 와 dagger2 를 사용하는 걸로 가자.
